language: python
sudo: false
python:
 - "2.7"
services:
  - redis-server
before_install:
  - scripts/travis_es.sh
  - /tmp/elasticsearch/elasticsearch-1.3.7/bin/elasticsearch -d -D es.path.data=/tmp -D es.gateway.type=none -D es.index.store.type=memory -D es.discovery.zen.ping.multicast.enabled=false
install:
  - pip install --no-deps --exists-action=w --download-cache=/tmp/pip-cache -r requirements/test.txt --find-links https://pyrepo.addons.mozilla.org/wheelhouse/
before_script:
  - mysql -e 'create database zamboni;'
  - flake8 .
script:
  - ./manage.py test lib mkt --noinput --logging-clear-handlers --with-blockage --with-nicedots
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always
cache:
    directories:
        - /tmp/elasticsearch
        - /tmp/pip-cache
